version: '3.8'
services:
  app-staging:
    image: crewflow-app:latest
    ports:
      - "3002:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:senha_segura_aqui@postgres-staging:5432/projetogran?schema=public
      - JWT_SECRET=crewflow-jwt-secret-key-staging-2024
      - NEXTAUTH_URL=http://localhost:3002
      - NODE_ENV=production
    container_name: crewflow-app-staging
    restart: unless-stopped
    networks:
      - projetogran_crewflow-network
    depends_on:
      - postgres-staging
    command: sh -c "npx prisma migrate deploy && npm start"

  postgres-staging:
    image: postgres:14
    container_name: postgres-staging
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha_segura_aqui
      - POSTGRES_DB=projetogran
    volumes:
      - postgres-staging-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - projetogran_crewflow-network

  pgadmin-staging:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-staging
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@crewflow.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5051:80"
    volumes:
      - pgadmin-staging-data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - projetogran_crewflow-network
    depends_on:
      - postgres-staging

networks:
  projetogran_crewflow-network:
    external: true

volumes:
  postgres-staging-data:
  pgadmin-staging-data: