-- CreateTable
CREATE TABLE "downtime_sheet" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "codProjeto" TEXT,
    "nomeProjeto" TEXT,
    "uptime" TEXT,
    "downtime" TEXT,
    "agEmbarque" INTEGER,
    "percentAgEmbarque" TEXT,
    "cadastro" INTEGER,
    "percentCadastro" TEXT,
    "medicina" INTEGER,
    "percentMedicina" TEXT,
    "treinamento" INTEGER,
    "percentTreinamento" TEXT,
    "atestado" INTEGER,
    "percentAtestado" TEXT,
    "falta" INTEGER,
    "percentFalta" TEXT,
    "demissao" INTEGER,
    "percentDemissao" TEXT,
    "dataUpload" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "nomeArquivo" TEXT,
    "uploadPor" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
